services:
  ak-monitor:
    container_name: ak-monitor
    image: ak-monitor:v0.0.5
    ports:
      - 3000:3000
    volumes:
      - ./config.json:/etc/akile-monitor/config.json:ro
      - ./data:/etc/akile-monitor/data:rw